spring.application.name=connect-drive


# Configuração do banco
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:connectdrive}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}


# JPA / Hibernate
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}


# Console H2
spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console

